### ISSUE TITLE
'Logged in as ' multiple times

### ISSUE THREAD

**Issue by N0v0cain3** [N0v0cain3/Kuizu#10]
<img width="244" alt="Screenshot 2021-05-27 at 7 31 17 PM" src="https://user-images.githubusercontent.com/50650500/119840038-41e12700-bf22-11eb-9578-161a9d4b92b0.png">

**Comment by N0v0cain3** [comment]
@Manasvi070902 can you check this

**Comment by Manasvi070902** [comment]
Fixed
