### ISSUE TITLE
Options not fetched properly

### ISSUE THREAD

**Issue by Manasvi070902** [N0v0cain3/Kuizu#11]
<img width="696" alt="Screenshot 2021-05-27 at 8 07 46 PM" src="https://user-images.githubusercontent.com/55336312/119845803-35ab9880-bf27-11eb-9920-ca3c574bba0b.png">

**Comment by N0v0cain3** [comment]
```
[
    {
        "options": [
            "option1",
            "option2",
            "option3",
            "option4"
        ],
        "_id": "60af8860922d7467da37ffcd",
        "title": "Question title"
    },
    {
        "options": [
            "option1",
            "option2",
            "option3",
            "option4"
        ],
        "_id": "60af8a16aa7bfa68478c9844",
        "title": "Question title 2"
    }
]
```
https://github.com/N0v0cain3/Kuizu/blob/5c9db8074ba9d1898aa505cbcf187485e9ab3d43/frontend/js/admin.js#L25

I think you are appending it in the same div.

**Comment by N0v0cain3** [comment]
Refer : 56fb68e236b1a9d22ea491763e613e430ec1de68
