### ISSUE TITLE
Route Not Found

### ISSUE THREAD

**Issue by kd1729** [N0v0cain3/Kuizu#19]
I have added all dependecies and  credentials in  .env file,
I have also added the start script  "start": "nodemon app.js"

After I run npm start this comes, and when I got to localhost:3000 , this messages shows up **{"error":{"message":"Route not found"}}**

---

![image](https://user-images.githubusercontent.com/55577276/144224002-6d4fb0f3-abd5-4a05-b1e3-87aa9dfd146f.png)

---

![image](https://user-images.githubusercontent.com/55577276/144223517-50512e98-9b53-4a90-9c13-217f60b16d21.png)

**Comment by N0v0cain3** [comment]
This is the health check route, It returns 404. 


If you have any other doubts dm me https://www.linkedin.com/in/shivam-mehta-b09724189/
